export const ProductService = {
    getProductsData() {
        return [
            {
                id: '1000',
                booking_code: 'f230fh0g3',
                departure: 'Banda Aceh',
                arrive: 'Bali',
                date_depart: '23 Juni 2023',
                date_arrive: '24 Juni 2023',
                time_depart: '23.30',
                time_arrive: '00.04',
                booking_date: 'Juni, 22 2003',
                price: 2500000,
                inventoryStatus: 'INSTOCK',
                class: 'Economy',
            },
            {
                id: '1000',
                booking_code: 'f230fh0g3',
                departure: 'Banda Aceh',
                arrive: 'Bali',
                date_depart: '23 Juni 2023',
                date_arrive: '24 Juni 2023',
                time_depart: '23.30',
                time_arrive: '00.04',
                booking_date: 'Juni, 22 2003',
                price: 2500000,
                inventoryStatus: 'INSTOCK',
                class: 'Economy',
            },
            {
                id: '1000',
                booking_code: 'f230fh0g3',
                departure: 'Banda Aceh',
                arrive: 'Bali',
                date_depart: '23 Juni 2023',
                date_arrive: '24 Juni 2023',
                time_depart: '23.30',
                time_arrive: '00.04',
                booking_date: 'Juni, 22 2003',
                price: 2500000,
                inventoryStatus: 'INSTOCK',
                class: 'Economy',
            },
            {
                id: '1000',
                booking_code: 'f230fh0g3',
                departure: 'Banda Aceh',
                arrive: 'Bali',
                date_depart: '23 Juni 2023',
                date_arrive: '24 Juni 2023',
                time_depart: '23.30',
                time_arrive: '00.04',
                booking_date: 'Juni, 22 2003',
                price: 2500000,
                inventoryStatus: 'INSTOCK',
                class: 'Economy',
            },
            {
                id: '1000',
                booking_code: 'f230fh0g3',
                departure: 'Banda Aceh',
                arrive: 'Bali',
                date_depart: '23 Juni 2023',
                date_arrive: '24 Juni 2023',
                time_depart: '23.30',
                time_arrive: '00.04',
                booking_date: 'Juni, 22 2003',
                price: 2500000,
                inventoryStatus: 'INSTOCK',
                class: 'Economy',
            },
            {
                id: '1000',
                booking_code: 'f230fh0g3',
                departure: 'Banda Aceh',
                arrive: 'Bali',
                date_depart: '23 Juni 2023',
                date_arrive: '24 Juni 2023',
                time_depart: '23.30',
                time_arrive: '00.04',
                booking_date: 'Juni, 22 2003',
                price: 2500000,
                inventoryStatus: 'INSTOCK',
                class: 'Economy',
            },
            {
                id: '1000',
                booking_code: 'f230fh0g3',
                departure: 'Banda Aceh',
                arrive: 'Bali',
                date_depart: '23 Juni 2023',
                date_arrive: '24 Juni 2023',
                time_depart: '23.30',
                time_arrive: '00.04',
                booking_date: 'Juni, 22 2003',
                price: 2500000,
                inventoryStatus: 'INSTOCK',
                class: 'Economy',
            },
            {
                id: '1000',
                booking_code: 'f230fh0g3',
                departure: 'Banda Aceh',
                arrive: 'Bali',
                date_depart: '23 Juni 2023',
                date_arrive: '24 Juni 2023',
                time_depart: '23.30',
                time_arrive: '00.04',
                booking_date: 'Juni, 22 2003',
                price: 2500000,
                inventoryStatus: 'INSTOCK',
                class: 'Economy',
            },
            {
                id: '1000',
                booking_code: 'f230fh0g3',
                departure: 'Banda Aceh',
                arrive: 'Bali',
                date_depart: '23 Juni 2023',
                date_arrive: '24 Juni 2023',
                time_depart: '23.30',
                time_arrive: '00.04',
                booking_date: 'Juni, 22 2003',
                price: 2500000,
                inventoryStatus: 'INSTOCK',
                class: 'Economy',
            },
            {
                id: '1000',
                booking_code: 'f230fh0g3',
                departure: 'Banda Aceh',
                arrive: 'Bali',
                date_depart: '23 Juni 2023',
                date_arrive: '24 Juni 2023',
                time_depart: '23.30',
                time_arrive: '00.04',

                booking_date: 'Juni, 22 2003',
                price: 2500000,
                inventoryStatus: 'INSTOCK',
                class: 'Economy',
            },
            {
                id: '1000',
                booking_code: 'f230fh0g3',
                departure: 'Banda Aceh',
                arrive: 'Bali',
                date_depart: '23 Juni 2023',
                date_arrive: '24 Juni 2023',
                time_depart: '23.30',
                time_arrive: '00.04',
                booking_date: 'Juni, 22 2003',
                price: 2500000,
                inventoryStatus: 'INSTOCK',
                class: 'Economy',
            },
            {
                id: '1000',
                booking_code: 'f230fh0g3',
                departure: 'Banda Aceh',
                arrive: 'Bali',
                date_depart: '23 Juni 2023',
                date_arrive: '24 Juni 2023',
                time_depart: '23.30',
                time_arrive: '00.04',
                booking_date: 'Juni, 22 2003',
                price: 2500000,
                inventoryStatus: 'INSTOCK',
                class: 'Economy',
            },
            {
                id: '1001',
                code: 'nvklal433',
                name: 'Black Watch',
                description: 'Product Description',
                image: 'black-watch.jpg',
                booking_date: 'Juni, 22 2003',
                price: 72,
                category: 'Accessories',
                quantity: 61,
                inventoryStatus: 'INSTOCK',
                rating: 4
            },
            {
                id: '1002',
                code: 'zz21cz3c1',
                name: 'Blue Band',
                description: 'Product Description',
                image: 'blue-band.jpg',
                booking_date: 'Juni, 22 2003',
                price: 79,
                category: 'Fitness',
                quantity: 2,
                inventoryStatus: 'LOWSTOCK',
                rating: 3
            },
            {
                id: '1003',
                code: '244wgerg2',
                name: 'Blue T-Shirt',
                description: 'Product Description',
                image: 'blue-t-shirt.jpg',
                booking_date: 'Juni, 22 2003',
                price: 29,
                category: 'Clothing',
                quantity: 25,
                inventoryStatus: 'INSTOCK',
                rating: 5
            },
            {
                id: '1004',
                code: 'h456wer53',
                name: 'Bracelet',
                description: 'Product Description',
                image: 'bracelet.jpg',
                booking_date: 'Juni, 22 2003',
                price: 15,
                category: 'Accessories',
                quantity: 73,
                inventoryStatus: 'INSTOCK',
                rating: 4
            }
        ];
    },

    getProductsWithOrdersData() {
        return [
            {
                id: '1000',
                booking_code: 'f230fh0g3',
                departure: 'Banda Aceh',
                airport_departure: 'Sultan Iskandar Muda - 1A',
                arrive: 'Bali',
                airport_arrive: 'I Gusti Ngurah Rai - 1C',
                date_depart: '23 Juni 2023',
                date_arrive: '24 Juni 2023',
                time_depart: '23.30',
                time_arrive: '00.04',
                booking_date: 'Juni, 22 2003',
                airplane_name : 'JET-V1',
                airplane_code : 'V1-101',
                booking_time: '20.04',
                price: 2500000,
                inventoryStatus: 'INSTOCK',
                class: 'Economy',
                trans_ID : 1,
                ticket_ID : 12345,
                payment_ID : 6789,
                // user_ID : 0987,
                status : 'ISSUED',
                total_price : 120000.0,
                orders: [
                    {
                        id: '1000-0',
                        age : 31,
                        name : "baby shark",
                        productCode: 'f230fh0g3',
                        bill:1700000,
                        date: '2020-09-13',
                        amount: 65,
                        quantity: 1,
                        customer: 'David James',
                        ticket_ID : 1,
                        seat_ID : 12,
                        flight_ID : '111',
                        date_of_purchase : '20-01-2003',
                        max_kg : 7.0,
                        type_of_class :'Business Class',
                        type_of_passenger :'Adult',
                        price : 200000.0,
                        passenger_ID : 678,
                    },
                    {
                        id: '1000-1',
                        age : 33,
                        name : "mommy shark",
                        productCode: 'f230fh0g3',
                        bill:1500000,
                        date: '2020-09-13',
                        amount: 65,
                        quantity: 1,
                        customer: 'David James',
                    },
                    {
                        id: '1000-1',
                        age : 13,
                        name : "mommy shark",
                        productCode: 'f230fh0g3',
                        bill:1500000,
                        date: '2020-09-13',
                        amount: 65,
                        quantity: 1,
                        customer: 'David James',
                    }
                ]
            },
            {
                id: '1001',
                booking_code: 'fsaf789af',
                departure: 'Surabaya',
                airport_departure: 'Juanda - 1A',
                arrive: 'Bali',
                airport_arrive: 'I Gusti Ngurah Rai - 1C',
                date_depart: '22 Juni 2023',
                date_arrive: '22 Juni 2023',
                time_depart: '20.30',
                time_arrive: '21.04',
                booking_date: 'Juni, 22 2003',
                airplane_name : 'Sukoi-V1',
                airplane_code : 'S2-107',
                booking_time: '20.04',
                price: 2000000,
                inventoryStatus: 'INSTOCK',
                class: 'Bisnis',
                status: 'CANCELLED',
                orders: [
                    {
                        id: '1001-0',
                        age : 3,
                        name : "baby shark",
                        productCode: 'f230fh0g3',
                        bill:1500000,
                        date: '2020-09-13',
                        amount: 65,
                        quantity: 1,
                        customer: 'David James',
                    },
                    {
                        id: '1001-1',
                        age : 33,
                        name : "mommy shark",
                        productCode: 'f230fh0g3',
                        bill:2500000,
                        date: '2020-09-13',
                        amount: 65,
                        quantity: 1,
                        customer: 'David James',
                    }
                ]
            },
            {
                id: '1002',
                booking_code: '78shg09',
                departure: 'Banda Aceh',
                airport_departure: 'Sultan Iskandar Muda - 1A',
                arrive: 'Surabaya',
                airport_arrive: 'Juand - 2A',
                date_depart: '24 September 2023',
                date_arrive: '24 Agustus 2023',
                time_depart: '12.30',
                time_arrive: '16.04',
                booking_date: 'Agustus, 22 2003',
                airplane_name : 'Tempur-A01',
                airplane_code : '2001-00',
                booking_time: '12.45',
                price: 3000000,
                inventoryStatus: 'INSTOCK',
                class: 'Economy',
                status: 'UNPAID',
                orders: [
                    {
                        id: '1002-0',
                        age : 3,
                        name : "baby shark",
                        productCode: 'f230fh0g3',
                        bill:1500000,
                        date: '2020-09-13',
                        amount: 65,
                        quantity: 1,
                        customer: 'David James',
                    },
                    {
                        id: '1002-1',
                        age : 33,
                        name : "mommy shark",
                        productCode: 'f230fh0g3',
                        bill:1500000,
                        date: '2020-09-13',
                        amount: 65,
                        quantity: 1,
                        customer: 'David James',
                    }
                ]
            },
            {
                id: '1003',
                booking_code: 'ask234dsc',
                departure: 'Jakarta',
                airport_departure: 'Soekarno Hatta - 3A',
                arrive: 'Jeddah, Arab Saudi',
                airport_arrive: 'King Abdul Aziz - 2C',
                date_depart: '4 Juni 2023',
                date_arrive: '4 Juni 2023',
                time_depart: '09.00',
                time_arrive: '23.00',
                booking_date: 'Januari, 25 2003',
                airplane_name : 'Garuda Indonesia',
                airplane_code : 'V1-101',
                booking_time: '20.04',
                price: 2500000,
                inventoryStatus: 'INSTOCK',
                class: 'Economy',
                status: 'UNPAID',
                orders: [
                    {
                        id: '1003-0',
                        age : 3,
                        name : "baby shark",
                        productCode: 'f230fh0g3',
                        bill:1500000,
                        date: '2020-09-13',
                        amount: 65,
                        quantity: 1,
                        customer: 'David James',
                    },
                    {
                        id: '1003-1',
                        age : 33,
                        name : "mommy shark",
                        productCode: 'f230fh0g3',
                        bill:1500000,
                        date: '2020-09-13',
                        amount: 65,
                        quantity: 1,
                        customer: 'David James',
                    }
                ]
            }
        ];
    },

    getProductsMini() {
        return Promise.resolve(this.getProductsData().slice(0, 5));
    },

    getProductsSmall() {
        return Promise.resolve(this.getProductsData().slice(0, 10));
    },

    getProducts() {
        return Promise.resolve(this.getProductsData());
    },

    getProductsWithOrdersSmall() {
        return Promise.resolve(this.getProductsWithOrdersData().slice(0, 10));
    },

    getProductsWithOrders() {
        return Promise.resolve(this.getProductsWithOrdersData());
    }
};

